### ISSUE TITLE
Fang's adaptive attack to Median and Trmean.

### ISSUE THREAD

**Issue by lishenghui** [vrt1shjwlkr/NDSS21-Model-Poisoning#2]
In `get_malicious_updates_fang_trmean` function, [`Fang's adaptive attack to Median and Trmean ](https://github.com/vrt1shjwlkr/NDSS21-Model-Poisoning/blob/main/cifar10/release-fedsgd-alexnet-trmean.ipynb), Cell 7, 

`mal_vec = (torch.stack([(deviation > 0).type(torch.FloatTensor)] * max_rand.shape[1]).T.cuda() * max_rand + torch.stack(
        [(deviation > 0).type(torch.FloatTensor)] * min_rand.shape[1]).T.cuda() * min_rand).T
`. 

Should it be
`mal_vec = (torch.stack([(deviation < 0).type(torch.FloatTensor)] * max_rand.shape[1]).T.cuda() * max_rand + torch.stack(
        [(deviation > 0).type(torch.FloatTensor)] * min_rand.shape[1]).T.cuda() * min_rand).T
` instead? As it should sample from [w_max, b * w_max] if `deviation < 0`.

**Comment by vrt1shjwlkr** [comment]
Hey @lishenghui, I think the current code should be correct, as it reproduces the results :) Plus, the "> 0" in both the places is addressed by the prior code which takes care of the signs based on how I define min_/max_. 

Please let me know if this does not address your concern and I can take a closer look!  You might as well try to run the code and see results.
